### ISSUE TITLE
Investigate long unexpected stacktraces

### ISSUE THREAD

**Issue by sgohlke** [dreamit-de/graphql-server#118]
In the test run there are some stacktraces that seem to be quite long and contain multiple references to the same line of code in the Express routing. We should investigate that. If necessary we should add an option to disable the stacktrace collection in some tests so they do not spam the log.

```
{
  "logger": "test-logger",
  "timestamp": "2023-01-31T09:00:27.471Z",
  "message": "Request could not be processed:  Syntax Error: Unexpected Name \"unknown\".",
  "level": "ERROR",
  "serviceName": "myTestService",
  "errorName": "SyntaxError",
  "stacktrace": "see below",
  "query": "unknown"
}
```

Stacktrace:
```

GraphQLError: Syntax Error: Unexpected Name \"unknown\".\n    
at syntaxError (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/graphql/error/syntaxError.js:15:10)\n    
at Parser.unexpected (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/graphql/language/parser.js:1458:41)\n   
at Parser.parseDefinition (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/graphql/language/parser.js:212:16)\n    
at Parser.many (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/graphql/language/parser.js:1511:26)\n    
at Parser.parseDocument (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/graphql/language/parser.js:122:25)\n    
at parse (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/graphql/language/parser.js:32:17)\n    
at GraphQLServer.parseFunction (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:333:27)\n    
at step (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6893:19)\n    
at Object.next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6659:14)\n    
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6593:39\n   
at new Promise (<anonymous>)\n    
at Object.<anonymous>.__awaiter (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6542:10)\n    
at GraphQLServer.executeRequestWithInfo (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:7492:12)\n
at GraphQLServer.executeRequestWithInfo (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:135:35)\n    
at step (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6893:19)\n    
at Object.next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6659:14)\n   
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6593:39\n    
at new Promise (<anonymous>)\n    
at Object.<anonymous>.__awaiter (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:6542:10)\n   
at GraphQLServer.executeRequestAndSendResponse (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/src/server/GraphQLServer.ts:7237:12)\n    
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/tests/server/GraphQLServer.executeRequest.integration.test.ts:65:42\n    
at step (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/tests/server/GraphQLServer.executeRequest.integration.test.ts:33:23)\n
at Object.next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/tests/server/GraphQLServer.executeRequest.integration.test.ts:14:53)\n    
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/tests/server/GraphQLServer.executeRequest.integration.test.ts:8:71\n    
at new Promise (<anonymous>)\n    
at Object.<anonymous>.__awaiter (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/tests/server/GraphQLServer.executeRequest.integration.test.ts:4:12)\n    
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/tests/server/GraphQLServer.executeRequest.integration.test.ts:57:65\n    at Layer.handle [as handle_request] (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/layer.js:95:5)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:144:13)\n   
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:140:7)\n    
at Route.dispatch (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/route.js:114:3)\n    
at Layer.handle [as handle_request] (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/layer.js:95:5)\n    
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/index.js:284:15\n    
at Function.process_params (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/index.js:346:12)\n    
at next (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/express/lib/router/index.js:280:10)\n    
at /Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/body-parser/lib/read.js:137:5\n    
at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    
at invokeCallback (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/raw-body/index.js:231:16)\n    
at done (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/raw-body/index.js:220:7)\n    
at IncomingMessage.onEnd (/Users/stefangohlke/work/develop/lottocom/dreamit-graphql-server/node_modules/raw-body/index.js:280:7)\n    
at IncomingMessage.emit (node:events:513:28)\n    
at endReadableNT (node:internal/streams/readable:1359:12)\n    
at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by sgohlke** [comment]
Findings:

In the Express next function there is an iteration through the router stack. This contains routes, middleware components and some internal logic, mainly query, expressInit, textParser (middleware) and bound dispatch (used for routing, here to “/graphql“)

The default option for Error.stackTraceLimit in NodeJS is 10. In Jest test runner it is set to 100. As the stacktrace information is not needed in the log output on the test run it should be removed where possible.
